### ISSUE TITLE
The way to generate glove.pkl for other datasets

### ISSUE THREAD

**Issue by lntzm** [minghangz/cpl#6]
Hi Author,
the provided `glove.pkl` for each dataset is different as it only contains the necessary vocabulary. Specially, it contains:
- the most common words for MLM, 
- the wtoi dictionary, 
- and the id2vec dictionary. 

I found the value of vectors is different from the standard `glove.840B.300d`. I want to known how to generate the glove vectors and has it finetuned already in each dataset? How can I build the vectors for other datasets?
Thanks!

**Comment by minghangz** [comment]
Hello, for ActivityNet Captions dataset, we use the `glove.pkl` file provided by SCN (https://github.com/ikuinen/semantic_completion_network/blob/master/data/activitynet/vocab.pkl). However, they do not provide this file for Charades-STA dataset. Thus, we build this file from the standard `glove.6B.300d`.

**Comment by lntzm** [comment]
thanks for your reply!

**Comment by Song200103** [comment]
> Hello, for ActivityNet Captions dataset, we use the `glove.pkl` file provided by SCN (https://github.com/ikuinen/semantic_completion_network/blob/master/data/activitynet/vocab.pkl). However, they do not provide this file for Charades-STA dataset. Thus, we build this file from the standard `glove.6B.300d`.

Hello ,could you please provide the code to build the 'glove.pkl' file for Charades-STA dataset? I really need it.  Look forward to your reply!

**Comment by minghangz** [comment]
> > Hello, for ActivityNet Captions dataset, we use the `glove.pkl` file provided by SCN (https://github.com/ikuinen/semantic_completion_network/blob/master/data/activitynet/vocab.pkl). However, they do not provide this file for Charades-STA dataset. Thus, we build this file from the standard `glove.6B.300d`.
> 
> Hello ,could you please provide the code to build the 'glove.pkl' file for Charades-STA dataset? I really need it. Look forward to your reply!

I have uploaded the [`vocab.py`](https://github.com/minghangz/cpl/blob/main/vocab.py). Please check it.
