### ISSUE TITLE
Charades test and train json files missing videos

### ISSUE THREAD

**Issue by sayaknag** [minghangz/cpl#8]
Did you train your model on a truncated version of Charades and Activitynet?

**Comment by minghangz** [comment]
Hello, we use the training and testing data provided by our baseline [SCN](https://github.com/ikuinen/semantic_completion_network/tree/master/data/charades_sta). The data provided by SCN does indeed have missed some videos compared to the official data, but the specific reasons for this are unclear to us. We train our model on this truncated version.
